// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBExcVJycNuIBbNNOVTmfa-OwOLh_yO_v4',
    appId: '1:343363417122:web:0bcfe0d712820a2196467b',
    messagingSenderId: '343363417122',
    projectId: 'antikafarm-1bb69',
    authDomain: 'antikafarm-1bb69.firebaseapp.com',
    storageBucket: 'antikafarm-1bb69.firebasestorage.app',
    measurementId: 'G-N3HQCPRSYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpgg4LRt3CgSgs6m0RSKEjvEoSA0JqQY',
    appId: '1:343363417122:android:a16790c98ff4888796467b',
    messagingSenderId: '343363417122',
    projectId: 'antikafarm-1bb69',
    storageBucket: 'antikafarm-1bb69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLam_a_YHRU6mGCJSUIZO8AdtW0myJaI',
    appId: '1:343363417122:ios:1cd037a1163ca86896467b',
    messagingSenderId: '343363417122',
    projectId: 'antikafarm-1bb69',
    storageBucket: 'antikafarm-1bb69.firebasestorage.app',
    iosBundleId: 'com.example.antikaFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLam_a_YHRU6mGCJSUIZO8AdtW0myJaI',
    appId: '1:343363417122:ios:1cd037a1163ca86896467b',
    messagingSenderId: '343363417122',
    projectId: 'antikafarm-1bb69',
    storageBucket: 'antikafarm-1bb69.firebasestorage.app',
    iosBundleId: 'com.example.antikaFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBExcVJycNuIBbNNOVTmfa-OwOLh_yO_v4',
    appId: '1:343363417122:web:d89263d39d73f8f196467b',
    messagingSenderId: '343363417122',
    projectId: 'antikafarm-1bb69',
    authDomain: 'antikafarm-1bb69.firebaseapp.com',
    storageBucket: 'antikafarm-1bb69.firebasestorage.app',
    measurementId: 'G-MJ8L9198XK',
  );
}
